import { useState } from 'react';
import { Notice } from '@/components/common/Ui';

const definitions = {
  courses: [ ['code','Mã khóa học'], ['slug','Đường dẫn (slug)'], ['title','Tên khóa học'], ['titleVi','Tên tiếng Việt',false], ['description','Mô tả','textarea'], ['descriptionVi','Mô tả tiếng Việt','textarea',false], ['level','Trình độ',['A0','A1','A2','B1','B2','C1']], ['estimatedMinutes','Thời lượng (phút)','number'], ['thumbnailUrl','URL ảnh bìa','text',false], ['learningOutcomes','Mục tiêu học tập','textarea',false] ],
  lessons: [ ['code','Mã bài học'], ['slug','Đường dẫn (slug)'], ['title','Tên bài học'], ['titleVi','Tên tiếng Việt',false], ['description','Mô tả','textarea',false], ['lessonType','Loại bài',['NORMAL','VOCABULARY','GRAMMAR','CONVERSATION','CULTURE','REVIEW']], ['estimatedMinutes','Thời lượng (phút)','number'], ['descriptionVi','Mô tả tiếng Việt','textarea',false], ['learningObjective','Mục tiêu học tập','textarea',false], ['learningObjectiveVi','Mục tiêu tiếng Việt','textarea',false] ],
  quizzes: [ ['title','Tên quiz'], ['titleVi','Tên tiếng Việt',false], ['description','Mô tả','textarea',false], ['descriptionVi','Mô tả tiếng Việt','textarea',false], ['quizType','Loại quiz',['LESSON','COURSE','PLACEMENT','PRACTICE']], ['courseId','ID khóa học','number',false], ['lessonId','ID bài học','number',false], ['passingScore','Điểm đạt (%)','number'], ['timeLimitMinutes','Giới hạn (phút)','number',false], ['maxAttempts','Số lần tối đa','number',false] ],
  modules: [ ['title','Tên module'], ['titleVi','Tên tiếng Việt',false], ['description','Mô tả','textarea',false], ['descriptionVi','Mô tả tiếng Việt','textarea',false] ],
};
const defaults = { courses:{level:'A1',estimatedMinutes:0,isFree:true}, lessons:{lessonType:'NORMAL',estimatedMinutes:10,prerequisiteIds:[]}, quizzes:{quizType:'PRACTICE',passingScore:70,timeLimitMinutes:null,maxAttempts:null,randomizeQuestions:false}, modules:{} };

export function ContentForm({ kind, initial = {}, onSave, onCancel }) {
  const [form,setForm] = useState({ ...defaults[kind], ...initial, estimatedMinutes:initial.estimatedMinutes ?? initial.estimatedDuration ?? defaults[kind]?.estimatedMinutes });
  const [busy,setBusy] = useState(false), [error,setError] = useState('');
  async function submit(event) { event.preventDefault(); setBusy(true); setError(''); try { const payload = Object.fromEntries(definitions[kind].map(([key,,type])=>[key,type==='number'?form[key]==null||form[key]===''?null:Number(form[key]):form[key]||''])); if(kind==='courses')payload.isFree=!!form.isFree;if(kind==='lessons')payload.prerequisiteIds=form.prerequisiteIds||[];if(kind==='quizzes')payload.randomizeQuestions=!!form.randomizeQuestions; await onSave(payload); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <form onSubmit={submit}><div className="form-grid">{definitions[kind].map(([key,label,type,required=true])=>{const optional=type===false||required===false;return <label key={key} className={type==='textarea'?'full-width':''}>{label}{Array.isArray(type)?<select disabled={busy} value={form[key]||type[0]} onChange={event=>setForm({...form,[key]:event.target.value})}>{type.map(option=><option key={option}>{option}</option>)}</select>:type==='textarea'?<textarea disabled={busy} required={!optional} rows={3} value={form[key]||''} onChange={event=>setForm({...form,[key]:event.target.value})}/>:<input disabled={busy} required={!optional} type={typeof type==='string'?type:'text'} min={key==='maxAttempts'||key==='timeLimitMinutes'?1:0} max={key==='passingScore'?100:undefined} pattern={key==='slug'?'[a-z0-9]+(?:-[a-z0-9]+)*':undefined} value={form[key]??''} onChange={event=>setForm({...form,[key]:event.target.value})}/>}</label>;})}</div>{kind==='courses'&&<label className="checkbox-row"><input type="checkbox" checked={!!form.isFree} onChange={event=>setForm({...form,isFree:event.target.checked})}/>Khóa học miễn phí</label>}{kind==='quizzes'&&<label className="checkbox-row"><input type="checkbox" checked={!!form.randomizeQuestions} onChange={event=>setForm({...form,randomizeQuestions:event.target.checked})}/>Xáo trộn câu hỏi</label>}{error&&<Notice kind="error">{error}</Notice>}<div className="form-actions actions"><button type="button" className="secondary" disabled={busy} onClick={onCancel}>Hủy</button><button disabled={busy}>{busy?'Đang lưu…':'Lưu thay đổi'}</button></div></form>;
}
