import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '@/application/context/AuthContext';
import { learnerService } from '@/services/learnerService';
import { PageHeader, Artwork, SpeakButton } from '@/components/common/Ui';
import { ProgressBar } from '@/components/common/ProgressBar';
export function HomePage() {
 const {user,isAuthenticated}=useAuth(); const [progress,setProgress]=useState(null); const [dashboardError,setDashboardError]=useState('');
 useEffect(()=>{if(isAuthenticated)learnerService.getProgressData().then(setProgress).catch(e=>setDashboardError(e.message));},[isAuthenticated]);
 if(!isAuthenticated)return <section className="welcome-page"><div className="welcome-hero"><div><p className="eyebrow">Learn Vietnamese · Live Vietnam</p><h1>Tiếng Việt cho<br/><em>những điều đời thường.</em></h1><p className="lead">Bài học ngắn, những câu chuyện gần gũi và một hành trình khám phá Việt Nam. Bắt đầu từ một lời chào.</p><div className="actions"><Link className="button" to="/register">Bắt đầu học miễn phí →</Link><Link className="button secondary" to="/courses">Khám phá khóa học</Link></div></div><div className="welcome-mission card"><Artwork kind="coffee"/><div><p className="eyebrow">Câu nói đầu tiên của bạn</p><h2>Cho tôi một cà phê sữa đá.</h2><p className="muted">One iced milk coffee, please.</p><SpeakButton text="Cho tôi một cà phê sữa đá"/></div></div></div><div className="welcome-links"><Link className="card" to="/courses"><span>01 · HỌC</span><h2>Từng chút tiếng Việt.</h2><p>Từ vựng, phát âm và tình huống thực tế.</p></Link><Link className="card" to="/explore"><span>02 · KHÁM PHÁ</span><h2>Một đất nước để gặp gỡ.</h2><p>Ngôn ngữ, văn hóa và những điểm đến.</p></Link><Link className="card" to="/ai-tutor"><span>03 · TRÒ CHUYỆN</span><h2>Tự tin tìm tiếng nói.</h2><p>Luyện tập cùng người bạn AI của bạn.</p></Link></div></section>;
 const dailyGoal=progress?.dailyGoalMinutes||15,today=progress?.todayMinutes||10,goalPercent=Math.min(100,Math.round(today/dailyGoal*100));
 const streak=progress?.streakCount??progress?.currentStreak??4,totalXp=progress?.totalXp??420;
 const currentLesson=progress?.currentLesson||{title:'Order your first cà phê sữa đá ☕',courseTitle:'Tiếng Việt Giao Tiếp Đời Sống A1',progressPercent:65,phraseVi:'Cho tôi một cà phê sữa đá.'};
 return <section className="dashboard-page"><PageHeader eyebrow="Hành trình tiếng Việt của bạn" title={`Xin chào, ${user?.fullName||user?.username||'Học viên'}!`} description="Luyện tập một chút hôm nay. Một thế giới mới ngày mai." actions={<span className="badge">🔥 {streak} ngày · {totalXp} XP</span>}/>{dashboardError&&<div className="ui-notice ui-notice--error" role="alert">{dashboardError}</div>}<div className="dashboard-grid"><div><section className="dashboard-continue"><div><p className="eyebrow">Tiếp nối câu chuyện của bạn</p><span className="badge">{currentLesson.courseTitle}</span><h2>Một chút<br/>hương vị Việt Nam.</h2><p>{currentLesson.title}</p><small>“{currentLesson.phraseVi||'Cho tôi một cà phê sữa đá.'}”</small><ProgressBar value={currentLesson.progressPercent} label="Tiến độ bài học"/><div className="actions"><Link className="button" to="/my-learning">Tiếp tục học →</Link><Link className="text-link" to="/courses">Xem khóa học</Link></div></div><Artwork kind="food-hero"/></section><h2>Chặng đường tiếp theo của bạn</h2><Link to="/explore/danang" className="dashboard-destination"><Artwork kind="coast"/><div><p className="eyebrow">Miền Trung Việt Nam</p><h2>Gặp nhau ở Đà Nẵng.</h2></div></Link></div><aside><section className="card dashboard-goal"><h2>Khoảnh khắc mỗi ngày</h2><div className="goal-ring" style={{'--goal':`${goalPercent}%`}}><strong>{today}<small> / {dailyGoal}</small></strong></div><p>{goalPercent>=100?'Bạn đã hoàn thành mục tiêu hôm nay!':`Còn ${Math.max(0,dailyGoal-today)} phút để ngày hôm nay thêm ý nghĩa.`}</p><Link className="text-link" to="/progress">Xem tiến độ →</Link></section><Link className="card dashboard-refresher" to="/vocabulary/review"><h2>Ôn lại một chút?</h2><p>{progress?.savedVocabCount||48} từ trong sổ tay của bạn.</p><span className="text-link">Ôn từ vựng →</span></Link><section className="card dashboard-ai"><span className="ai-orb">✣</span><p className="eyebrow">Người bạn AI của bạn</p><h2>Cứ thử nói nhé.</h2><p>Luyện tập thoải mái, từng câu một.</p><Link className="button secondary" to="/ai-tutor">Bắt đầu trò chuyện</Link><Link className="text-link" to="/ai-scenarios">Chọn kịch bản Roleplay →</Link></section></aside></div><section className="dashboard-recent"><h2>Những bước nhỏ gần đây</h2>{(progress?.recentActivities||[{id:1,title:'Hoàn thành bài học: Gọi cà phê sữa đá',xp:50,time:'2 giờ trước'},{id:2,title:'Ôn tập 10 từ vựng: Chào hỏi hàng ngày',xp:20,time:'Hôm qua'},{id:3,title:'Đạt chuỗi học 4 ngày liên tiếp 🔥',xp:30,time:'Hôm qua'}]).map(act=><div className="list-row" key={act.id}><div><strong>{act.title}</strong><small>{act.time}</small></div><span className="badge">+{act.xp} XP</span></div>)}</section></section>;
}
