import fs from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
const change=async(path,fn)=>{const text=await fs.readFile(path,'utf8');await fs.writeFile(path,fn(text));};
for(const path of ['src/pages/RegisterPage.jsx',...['ForgotPasswordPage','ResetPasswordPage','VerifyEmailPage','OnboardingPage'].map(name=>`src/pages/auth/${name}.jsx`)]){
 await change(path,text=>"import { AuthHeader } from '@/components/auth/AuthHeader';\n"+text.replace(/<div className="auth-brand-row">[\s\S]*?<span className="auth-brand-badge">[\s\S]*?<\/span>\s*<\/div>/,'<AuthHeader />'));
}
// Keep the recognizable Google mark; it is not a theme swatch.
for(const path of ['src/pages/LoginPage.jsx','src/pages/RegisterPage.jsx']){
 const original=execFileSync('git',['show',`HEAD:${path}`],{encoding:'utf8'});
 const paths=[...original.matchAll(/<path[^>]*fill="#[^>]*\/>/g)].map(match=>match[0]);
 await change(path,text=>{let index=0;return text.replace(/<path[^>]*fill="var\(--color-[^>]*\/>/g,match=>paths[index++]||match);});
}
const files=async(dir)=>{let result=[];for(const file of await fs.readdir(dir,{withFileTypes:true})){const path=`${dir}/${file.name}`;if(file.isDirectory())result.push(...await files(path));else if(path.endsWith('.jsx'))result.push(path);}return result;};
for(const path of await files('src/pages'))await change(path,text=>text.replace(/(border(?:Top|Bottom|Left|Right)?\s*:\s*['"])([^'"]*?)#[0-9a-f]{3,8}(['"])/gi,'$1$2var(--color-border)$3'));
await change('src/pages/roleplay/RoleplayResultPage.jsx',text=>"import { EmptyState } from '@/components/common/Ui';\n"+text.replace("if (!result) return null;",'if (!result) return <EmptyState title="Chưa có kết quả phiên hội thoại" description="Hoàn thành một cuộc trò chuyện để xem đánh giá."><Link className="button" to="/ai-scenarios">Chọn kịch bản →</Link></EmptyState>;').replace("e.message || 'Thành công'","e.message || 'Không thể lưu từ vựng.'"));
await change('src/pages/quiz/QuizPages.jsx',text=>text.replace('if (answerPresent(answer)) await contentService.answer(attempt.id, question.questionId, answer);','if (answer !== question.answer) await contentService.answer(attempt.id, question.questionId, answerPresent(answer) ? answer : null);'));
await change('src/pages/admin/AdminQuizPages.jsx',text=>text.replace('{questions[index].audioUrl&&','{questions[index].imageUrl&&<img className="question-media" src={questions[index].imageUrl} alt="Hình minh họa câu hỏi"/>}{questions[index].audioUrl&&'));
await change('src/components/admin/ContentForm.jsx',text=>text.replace("['thumbnailUrl','URL ảnh bìa','url',false]","['thumbnailUrl','URL ảnh bìa','text',false]").replace("['learningObjective','Mục tiêu học tập','textarea',false]","['descriptionVi','Mô tả tiếng Việt','textarea',false], ['learningObjective','Mục tiêu học tập','textarea',false], ['learningObjectiveVi','Mục tiêu tiếng Việt','textarea',false]").replace("modules: [ ['title','Tên module'], ['titleVi','Tên tiếng Việt',false], ['description','Mô tả','textarea',false] ]","modules: [ ['title','Tên module'], ['titleVi','Tên tiếng Việt',false], ['description','Mô tả','textarea',false], ['descriptionVi','Mô tả tiếng Việt','textarea',false] ]"));
await change('src/pages/admin/AdminContentPages.jsx',text=>text.replace('grammarTopicIds:[],...initial','...initial,grammarTopicIds:initial.grammarTopicIds||initial.grammarTopics?.map(topic=>topic.id)||[]').replace('<label>Nội dung hoạt động (JSON)>','<label>Nội dung hoạt động (JSON)>'));
await change('src/pages/admin/AdminSettingsPage.jsx',text=>text.replace("const [msg, setMsg] = useState('');","const [msg, setMsg] = useState('');\n  const [error,setError] = useState('');\n  const [busy,setBusy] = useState(false);").replace('adminService.getSystemSettings().then(setSettings);','adminService.getSystemSettings().then(setSettings).catch(err=>setError(err.message));').replace('const res = await adminService.updateSystemSettings(settings);',"setBusy(true);setError('');\n    try {const res = await adminService.updateSystemSettings(settings);").replace("setTimeout(() => setMsg(''), 3000);","setTimeout(() => setMsg(''), 3000);\n    }catch(err){setError(err.message);}finally{setBusy(false);}").replace('if (!settings) return <div>','if (!settings) return <div className="state" role={error?"alert":"status"}>{error || ').replace('Đang tải cấu hình hệ thống…</div>;','"Đang tải cấu hình hệ thống…"}</div>;').replace('{msg && (','{error && <div className="ui-notice ui-notice--error" role="alert">{error}</div>}\n      {msg && (').replace('type="submit"\n          style','type="submit" disabled={busy}\n          style'));
await change('src/pages/admin/AdminUserDetailPage.jsx',text=>text.replace('const res = await adminService.updateUserRole(id, selectedRole);','try {const res = await adminService.updateUserRole(id, selectedRole);').replace("setTimeout(() => setMsg(''), 3000);","setTimeout(() => setMsg(''), 3000); }catch(error){setMsg(error.message);}").replace('if (!user) return <div>Đang tải chi tiết người dùng…</div>;','if (!user) return <div className="state" role={msg?"alert":"status"}>{msg || "Đang tải chi tiết người dùng…"}</div>;'));
