import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { PageHeader, Artwork, Tabs, Notice, EmptyState } from '@/components/common/Ui';
import { cultureService } from '@/services/cultureService';
import { SpeakButton } from '@/components/common/Ui';

const destinations = [
  { id: 'hcmc', name: 'TP. Hồ Chí Minh', region: 'Miền Nam', art: 'village', description: 'Một thành phố không ngừng gửi lời chào.' },
  { id: 'mientay', name: 'Đồng bằng sông Cửu Long', region: 'Miền Nam', art: 'coast', description: 'Nhịp sống theo những dòng sông.' },
  { id: 'dalat', name: 'Đà Lạt', region: 'Tây Nguyên', art: 'village', description: 'Rừng thông, sương sớm và những cuộc trò chuyện ấm áp.' },
  { id: 'nhatrang', name: 'Nha Trang', region: 'Duyên hải Nam Trung Bộ', art: 'coast', description: 'Một chút nắng trong từng câu nói.' },
  { id: 'danang', name: 'Đà Nẵng', region: 'Miền Trung', art: 'coast', description: 'Nơi núi gặp biển.' },
  { id: 'hoian', name: 'Hội An', region: 'Miền Trung', art: 'lanterns', description: 'Những câu chuyện nhỏ dưới ánh đèn lồng.' },
  { id: 'hue', name: 'Huế', region: 'Miền Trung', art: 'village', description: 'Ngôn ngữ dịu dàng bên dòng Hương.' },
  { id: 'hanoi', name: 'Hà Nội', region: 'Miền Bắc', art: 'coffee', description: 'Một tách cà phê và những câu chuyện phố phường.' },
  { id: 'halong', name: 'Hạ Long', region: 'Miền Bắc', art: 'coast', description: 'Một chân trời để khám phá.' },
  { id: 'sapa', name: 'Sa Pa', region: 'Miền Bắc', art: 'village', description: 'Gặp gỡ những sắc màu trên miền núi.' },
];
export function ExploreVietnamPage() {
  return <section><PageHeader eyebrow="Ngôn ngữ chỉ là điểm bắt đầu" title="Khám phá Việt Nam" description="Học ngôn ngữ. Gặp gỡ văn hóa. Cảm thấy gần gũi hơn mỗi ngày." actions={<Link className="button secondary" to="/achievements">Hộ chiếu của bạn →</Link>} /><Notice>Hành trình minh họa theo thiết kế. Xem thành tích để theo dõi những dấu mốc đã được hệ thống ghi nhận.</Notice><div className="journey-board card"><aside className="journey-map"><p className="eyebrow">VIỆT NAM · VIET NAM</p><img src="/design/vietnam-map.svg" alt="Bản đồ hành trình Việt Nam" /><div><p className="eyebrow">Chặng đường tiếp theo</p><h2>Một đất nước để khám phá.<br/>Một ngôn ngữ để sống cùng.</h2><p className="muted">Mỗi điểm đến mang một từ mới, một hương vị mới và một góc nhìn mới.</p></div></aside><div className="journey-stops">{destinations.map((destination, index) => <Link className="journey-stop" key={destination.id} to={`/explore/${destination.id}`}><span className="journey-dot" /><div className="journey-thumbnail"><Artwork kind={destination.art} /></div><div><p className="eyebrow">{destination.region}</p><h2>{destination.name}</h2><p>{destination.description}</p><small>Ngôn ngữ · Văn hóa · Luyện tập</small></div><span className="journey-number">{String(index + 1).padStart(2, '0')} →</span></Link>)}</div></div></section>;
}
export function DestinationDetailPage() {
  const { id } = useParams(); const destination = destinations.find(item => item.id === id); const [tab, setTab] = useState('learn');
  if (!destination) return <EmptyState title="Không tìm thấy điểm đến"><Link className="button" to="/explore">Về hành trình</Link></EmptyState>;
  const articles = cultureService.listArticles({ destination: id });
  return <section><Link className="text-link" to="/explore">← Hành trình Việt Nam</Link><div className="destination-hero card"><div><p className="eyebrow">{destination.region}</p><h1>{destination.name}</h1><p className="lead">{destination.description}</p><p className="muted">Khám phá ngôn ngữ, câu chuyện văn hóa và những tình huống đời thường.</p><Link className="button" to="/courses">Tiếp tục học →</Link></div><Artwork kind={destination.art} /></div><Tabs label="Nội dung điểm đến" value={tab} onChange={setTab} items={[{id:'learn',label:'Học tiếng Việt'},{id:'local',label:'Ngôn ngữ địa phương'},{id:'culture',label:'Văn hóa'},{id:'practice',label:'Luyện tập'}]} /><div className="split-grid"><div>{tab==='learn'&&<><h2>Tiếng Việt cho chuyến đi</h2>{['Gọi món ăn','Hỏi đường','Nhận phòng khách sạn'].map((title,index)=><Link className="list-row" key={title} to="/courses"><div><span className="badge">{index+1}</span> <strong>{title}</strong><small>Khám phá các bài học giao tiếp liên quan</small></div><span>→</span></Link>)}</>}{tab==='local'&&<div className="card"><h2>Những từ mang theo</h2><p className="muted">Nội dung minh họa từ thiết kế.</p>{destination.region==='Miền Trung'?[{word:'răng',meaning:'sao / why'},{word:'mô',meaning:'đâu / where'}].map(word=><div className="list-row" key={word.word}><div><h2>{word.word}</h2><small>{word.meaning} · Tiếng Việt miền Trung</small></div><SpeakButton text={word.word}/></div>):<EmptyState title="Chưa có bộ từ địa phương cho điểm đến này"><Link className="text-link" to="/ai-tutor">Luyện tiếng Việt với AI Tutor →</Link></EmptyState>}</div>}{tab==='culture'&&<><h2>Câu chuyện từ {destination.name}</h2>{articles.length?articles.map(article=><Link className="list-row" key={article.id} to={`/culture/${article.id}`}><div><strong>{article.title}</strong><small>{article.readTime}</small></div><span>→</span></Link>):<EmptyState title="Khám phá những câu chuyện Việt Nam"><Link className="button secondary" to="/culture">Thư viện văn hóa</Link></EmptyState>}</>}{tab==='practice'&&<div className="card"><h2>Một cuộc trò chuyện để bắt đầu</h2><p className="lead">Luyện các tình huống đời thường, gọi món và trò chuyện với người bản địa.</p><div className="actions"><Link className="button" to="/ai-scenarios">Chọn kịch bản Roleplay →</Link><Link className="button secondary" to="/ai-tutor">Hỏi AI Tutor</Link></div></div>}</div><aside className="card"><p className="eyebrow">Một chút văn hóa</p><h2>Chậm lại, gặp gỡ nhiều hơn.</h2><p className="muted">Khám phá đời sống địa phương qua từng bài học và câu chuyện.</p><Link className="text-link" to="/achievements">Xem hộ chiếu của bạn →</Link></aside></div></section>;
}
