import { BilingualText, bilingualLabel } from '@/components/common/BilingualText';
import { useCallback, useEffect, useState } from 'react';
import { adminService } from '@/services/adminService';

const empty = { event: '', points: 0, limitPerDay: '', antiSpam: '' };
export function AdminXpRulesPage() {
  const [items, setItems] = useState([]); const [draft, setDraft] = useState(empty); const [editing, setEditing] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { setItems(await adminService.getXpRules()); setError(''); } catch (e) { setError(e.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const submit = async (e) => { e.preventDefault(); try { editing ? await adminService.updateXpRule(editing, draft) : await adminService.createXpRule(draft); setEditing(null); setDraft(empty); load(); } catch (err) { setError(err.message); } };
  const edit = item => { setEditing(item.id); setDraft({ event: item.event || item.eventType || '', points: item.points ?? item.xpAmount ?? 0, limitPerDay: item.limitPerDay || '', antiSpam: item.antiSpam || '' }); };
  const remove = async id => { if (!window.confirm('Xóa quy tắc XP này?')) return; try { await adminService.deleteXpRule(id); load(); } catch (e) { setError(e.message); } };
  return <div><h1><BilingualText>{"Quy tắc cộng điểm XP"}</BilingualText></h1><p className="lead"><BilingualText>{"Quản lý điểm thưởng cho từng hoạt động học tập."}</BilingualText></p>{error && <div className="state" role="alert"><BilingualText>{error}</BilingualText></div>}
    <form className="admin-card" onSubmit={submit} style={{ display: 'grid', gridTemplateColumns: '2fr 1fr 1fr', gap: 12, marginBottom: 20 }}><input placeholder={bilingualLabel("Sự kiện")} value={draft.event} onChange={e => setDraft({ ...draft, event: e.target.value })} required /><input type="number" placeholder="XP" value={draft.points} onChange={e => setDraft({ ...draft, points: Number(e.target.value) })} required /><input placeholder={bilingualLabel("Giới hạn/ngày")} value={draft.limitPerDay} onChange={e => setDraft({ ...draft, limitPerDay: e.target.value })} /><input style={{ gridColumn: '1 / -1' }} placeholder={bilingualLabel("Cơ chế chống spam")} value={draft.antiSpam} onChange={e => setDraft({ ...draft, antiSpam: e.target.value })} /><div className="actions"><button><BilingualText>{editing ? 'Lưu thay đổi' : 'Thêm quy tắc'}</BilingualText></button>{editing && <button type="button" className="secondary" onClick={() => { setEditing(null); setDraft(empty); }}><BilingualText>{"Hủy"}</BilingualText></button>}</div></form>
    {loading ? <div className="state"><BilingualText>{"Đang tải…"}</BilingualText></div> : items.length === 0 ? <div className="state"><BilingualText>{"Chưa có quy tắc XP."}</BilingualText></div> : <div className="admin-card" style={{ padding: 0, overflowX: 'auto' }}><table className="admin-table"><thead><tr><th><BilingualText>{"Sự kiện"}</BilingualText></th><th><BilingualText>{"Điểm XP"}</BilingualText></th><th><BilingualText>{"Giới hạn"}</BilingualText></th><th><BilingualText>{"Chống spam"}</BilingualText></th><th><BilingualText>{"Thao tác"}</BilingualText></th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.event || item.eventType}</td><td>+{item.points ?? item.xpAmount} XP</td><td>{item.limitPerDay || '—'}</td><td>{item.antiSpam || '—'}</td><td><button className="secondary" onClick={() => edit(item)}><BilingualText>{"Sửa"}</BilingualText></button>{' '}<button className="danger" onClick={() => remove(item.id)}><BilingualText>{"Xóa"}</BilingualText></button></td></tr>)}</tbody></table></div>}
  </div>;
}
