import { BilingualText } from '@/components/common/BilingualText';
import { ContentImage } from '@/components/common/ContentImage';
import { useState } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { cultureService } from '@/services/cultureService';
import { vocabularyService } from '@/services/vocabularyService';
import { aiTutorService } from '@/services/aiTutorService';
import { Breadcrumb, SpeakButton, Notice, EmptyState } from '@/components/common/Ui';
import { RichText } from '@/components/common/RichText';

export function CultureDetailPage(){
 const{id}=useParams();const navigate=useNavigate();const article=cultureService.getArticle(id),relatedArticles=cultureService.getRelatedArticles(id);
 const[toastMessage,setToastMessage]=useState('');
 if(!article)return <EmptyState title="Không tìm thấy bài viết văn hóa"><Link className="button" to="/culture"><BilingualText>{"Về thư viện văn hóa"}</BilingualText></Link></EmptyState>;
 const showToast=message=>{setToastMessage(message);setTimeout(()=>setToastMessage(''),3500);};
 async function save(phrase){try{await vocabularyService.add({word:phrase.word,meaning:phrase.meaning,notes:`Từ vựng văn hóa: ${article.title} (${phrase.context||''})`});showToast(`Đã lưu “${phrase.word}” vào sổ từ vựng.`);}catch(err){showToast(`Không lưu được từ vựng: ${err.message}`);}}
 function ask(){aiTutorService.createSession('culture_guide',`Tìm hiểu: ${article.title.slice(0,24)}...`);navigate('/ai-tutor');}
 return <article className="culture-detail-page"><Breadcrumb items={[{label:'Văn hóa',to:'/culture'},{label:article.categoryName}]}/><p className="eyebrow">{article.categoryName} · {article.destinationName}</p><h1><BilingualText vi={article.titleVi || article.title} en={article.title} /></h1><p className="lead">{article.subtitle}</p><p className="muted">{article.author} · {article.authorRole} · {article.publishedDate} · {article.readTime}</p>{toastMessage&&<Notice>{toastMessage}</Notice>}<div className="culture-cover"><ContentImage src={article.coverImage} alt={article.title} className="figma-art" loading="eager"/></div><div className="culture-detail-layout"><div><RichText text={article.content}/><section className="culture-phrases"><h2><BilingualText>{"Những cụm từ hữu ích"}</BilingualText></h2><p className="muted"><BilingualText>{"Lắng nghe và mang theo những từ mới."}</BilingualText></p>{article.usefulPhrases?.map((phrase,index)=><div className="list-row" key={index}><div><strong>{phrase.word}</strong><small>{phrase.pronunciation} · {phrase.meaning}</small>{phrase.context&&<p className="muted">{phrase.context}</p>}</div><div className="actions"><SpeakButton text={phrase.word} audioUrl={phrase.audioUrl}/><button className="secondary" onClick={()=>save(phrase)}><BilingualText>{"Lưu từ"}</BilingualText></button></div></div>)}</section><div className="story-callout"><div><h3><BilingualText>{"Muốn biết thêm về câu chuyện?"}</BilingualText></h3><p className="muted"><BilingualText>{"Cùng AI Tutor tìm hiểu về văn hóa Việt Nam."}</BilingualText></p></div><button onClick={ask}><BilingualText>{"Hỏi AI Tutor →"}</BilingualText></button></div></div><aside><section className="card culture-note"><p className="eyebrow"><BilingualText>{"Góc văn hóa"}</BilingualText></p><h2><BilingualText>{"Dành một chút thời gian."}</BilingualText></h2><p className="muted"><BilingualText>{"Từng câu chuyện nhỏ giúp ngôn ngữ trở nên gần hơn."}</BilingualText></p><button className="secondary" onClick={ask}><BilingualText>{"Hỏi về câu chuyện này"}</BilingualText></button></section><section className="card"><h2>{article.destinationName}</h2><Link className="text-link" to={article.destination && article.destination !== 'all' ? `/explore/${article.destination}` : '/explore'}><BilingualText>{"Khám phá điểm đến →"}</BilingualText></Link></section>{relatedArticles.length>0&&<section className="card"><h2><BilingualText>{"Câu chuyện liên quan"}</BilingualText></h2>{relatedArticles.map(related=><Link className="text-link" key={related.id} to={`/culture/${related.id}`}><BilingualText vi={related.titleVi || related.title} en={related.title} /> →</Link>)}</section>}</aside></div></article>;
}
