import { BilingualText, bilingualLabel } from '@/components/common/BilingualText';
import { ContentImage } from '@/components/common/ContentImage';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { cultureService } from '@/services/cultureService';
import { PageHeader, Tabs, EmptyState } from '@/components/common/Ui';

export function CultureExplorePage(){
 const[search,setSearch]=useState(''),[selectedCategory,setSelectedCategory]=useState('all'),[selectedDestination,setSelectedDestination]=useState('all');
 const categories=cultureService.getCategories(),destinations=cultureService.getDestinations();
 const articles=cultureService.listArticles({search,category:selectedCategory,destination:selectedDestination});
 const featured=cultureService.getFeaturedArticles()[0];
 return <section className="p4-container culture-page"><PageHeader eyebrow="Nhiều hơn những từ ngữ" title="Khám phá văn hóa Việt Nam" description="Ngôn ngữ trở nên gần gũi khi bạn biết những câu chuyện phía sau."/>{!search&&selectedCategory==='all'&&selectedDestination==='all'&&featured&&<Link className="culture-feature" to={`/culture/${featured.id}`}><ContentImage src={featured.coverImage} alt={featured.title} className="figma-art" loading="eager"/><div><span className="badge">{featured.categoryName}</span><h2><BilingualText vi={featured.titleVi || featured.title} en={featured.title} /></h2><p>{featured.summary}</p><span><BilingualText>{"Khám phá câu chuyện →"}</BilingualText></span></div></Link>}
 <div className="library-toolbar"><Tabs label="Chủ đề văn hóa" value={selectedCategory} onChange={setSelectedCategory} items={categories.map(category=>({id:category.id,label:category.label}))}/><input aria-label="Tìm câu chuyện văn hóa" placeholder={bilingualLabel("⌕ Tìm câu chuyện…")} value={search} onChange={event=>setSearch(event.target.value)}/></div><div className="culture-destination-filter"><label><BilingualText>{"Điểm đến"}</BilingualText><select value={selectedDestination} onChange={event=>setSelectedDestination(event.target.value)}>{destinations.map(destination=><option key={destination.id} value={destination.id}>{bilingualLabel(destination.label)}</option>)}</select></label><span className="muted">{articles.length}<BilingualText>{"câu chuyện"}</BilingualText></span>{(search||selectedCategory!=='all'||selectedDestination!=='all')&&<button className="secondary" onClick={()=>{setSearch('');setSelectedCategory('all');setSelectedDestination('all');}}><BilingualText>{"Xóa bộ lọc"}</BilingualText></button>}</div>
 {articles.length?<div className="culture-grid">{articles.map(article=><Link className="card culture-story-card" key={article.id} to={`/culture/${article.id}`}><ContentImage src={article.coverImage} alt={article.title} className="figma-art"/><div><p className="eyebrow">{article.categoryName} · {article.readTime}</p><h3><BilingualText vi={article.titleVi || article.title} en={article.title} /></h3><p>{article.summary}</p><span className="text-link"><BilingualText>{"Khám phá câu chuyện →"}</BilingualText></span><small>{article.destinationName} · {article.publishedDate}</small></div></Link>)}</div>:<EmptyState title="Không tìm thấy câu chuyện phù hợp" description="Thử một từ khóa, chủ đề hoặc điểm đến khác."/>}</section>;
}
